language: haxe

sudo: false

haxe:
  - "3.2.1"
  - "3.4.0-rc.1"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install hxnodejs
  - haxelib dev hxnodejs-serialport .

script:
  - haxe --cwd example/ build.hxml
